# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: ğŸ“ï¸ Courses
    url: post
    weight: 10
  - name: ğŸ“šï¸ Books
    url: '#books'
    weight: 20
  - name: ğŸ“ƒ Articles
    url: 
    weight: 30
  - name: âœğŸ» WikiNotes
    url: 
    weight: 40
  - name: News
    url: post
    weight: 90
  - name: ğŸ‘¥ Team
    url: people
    weight: 60
  - name: Events
    url: event
    weight: 100
  - name: Publications
    url: publication
    weight: 500
  - name: ğŸ“§ Contact
    url: contact
    weight: 60
